### ISSUE TITLE
NameSpaceの選択画面の見た目

### ISSUE THREAD

**Issue by takuto0404** [takuto0404/MermaidMaker#1]

**Comment by AtaruMatsudaira** [comment]
スクショ欲しい😢

**Comment by takuto0404** [comment]
<img width="320" alt="スクリーンショット 2023-08-09 21 37 12" src="https://github.com/takuto0404/MermaidMaker/assets/103303559/281293f2-df94-44a9-b7ec-3f2058f14aeb">
